services:
  dev-db:
    container_name: dev-db
    image: postgres:16
    ports:
      - 5500:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root@123
      POSTGRES_DB: quick-learn
    networks:
      - quick-learn

networks:
  quick-learn:
