services:
  quick-learn:
    image: postgres:16
    ports:
      - 5500:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root@123
      POSTGRES_DB: bugplot
    networks:
      - quick-learn

networks:
  quick-learn:
