services:
  frontend:
    container_name: frontend
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/quick-learn-frontend/Dockerfile
    image: quick-learn-frontend:nx-dev
    ports:
      - 80:3000
    env_file:
      - path: ./apps/quick-learn-frontend/.env
    networks:
      - quick-learn
    depends_on:
      - backend
    restart: on-failure

  backend:
    container_name: backend
    build:
      context: ./
      cache_from:
        - quick-learn:nx-base
      dockerfile: ./apps/quick-learn-backend/Dockerfile
    image: quick-learn-backend:nx-dev
    ports:
      - 3001:3001
    env_file:
      - path: ./apps/quick-learn-backend/.env.production
    networks:
      - quick-learn
    restart: on-failure

networks:
  quick-learn:
