name: Lint

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  lint-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npx nx lint quick-learn-backend

      - name: Check formatting
        run: npx nx format:check quick-learn-backend

  lint-frontend:
    runs-on: ubuntu-22.04
    steps:
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npx nx lint quick-learn-frontend

      - name: Check formatting
        run: npx nx format:check quick-learn-frontend
